apiVersion: v1
kind: Service
metadata:
  name: conges-app-service
spec:
  selector:
    app: conges-app
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 6000  
      nodePort: 30080  
  type: NodePort
